var myJSONdata = {
    "myText": [
        { "line" : "KSIĘGA PIERWSZA"},
        { "line" : "GOSPODARSTWO"},
        { "line" : "Treść:"},
        { "line" : "Powrót panicza - Spotkanie się najpierwsze w pokoiku, drugie u stołu - Ważna Sędziego nauka o grzeczności - Podkomorzego uwagi polityczne nad modami - Początek sporu o Kusego i Sokoła - Żale Wojskiego - Ostatni Woźny Trybunału - Rzut oka na ówczesny stan polityczny Litwy i Europy."},
        { "line" : "Litwo! Ojczyzno moja! ty jesteś jak zdrowie."},
        { "line" : "Ile cię trzeba cenić, ten tylko się dowie,"},
        { "line" : "Kto cię stracił. Dziś piękność twą w całej ozdobie"},
        { "line" : "Widzę i opisuję, bo tęsknię po tobie."},
        { "line" : "Panno Święta, co jasnej bronisz Częstochowy"},
        { "line" : "I w Ostrej świecisz Bramie! Ty, co gród zamkowy"},
        { "line" : "Nowogródzki ochraniasz z jego wiernym ludem!"},
        { "line" : "Jak mnie dziecko do zdrowia powróciłaś cudem"},
        { "line" : "(Gdy od płaczącej matki pod Twoją opiekę"},
        { "line" : "Ofiarowany, martwą podniosłem powiekę"},
        { "line" : "I zaraz mogłem pieszo do Twych świątyń progu"},
        { "line" : "Iść za wrócone życie podziękować Bogu),"},
        { "line" : "Tak nas powrócisz cudem na Ojczyzny łono."},
        { "line" : "Tymczasem przenoś moję duszę utęsknioną"},
        { "line" : "Do tych pagórków leśnych, do tych łąk zielonych,"},
        { "line" : "Szeroko nad błękitnym Niemnem rozciągnionych;"},
        { "line" : "Do tych pól malowanych zbożem rozmaitem,"},
        { "line" : "Wyzłacanych pszenicą, posrebrzanych żytem;"},
        { "line" : "Gdzie bursztynowy świerzop, gryka jak śnieg biała,"},
        { "line" : "Gdzie panieńskim rumieńcem dzięcielina pała,"},
        { "line" : "A wszystko przepasane, jakby wstęgą, miedzą"},
        { "line" : "Zieloną, na niej z rzadka ciche grusze siedzą."},
        { "line" : "Śród takich pól przed laty, nad brzegiem ruczaju,"},
        { "line" : "Na pagórku niewielkim, we brzozowym gaju,"},
        { "line" : "Stał dwór szlachecki, z drzewa, lecz podmurowany;"},
        { "line" : "Świeciły się z daleka pobielane ściany,"},
        { "line" : "Tym bielsze, że odbite od ciemnej zieleni"},
        { "line" : "Topoli, co go bronią od wiatrów jesieni."},
        { "line" : "Dóm mieszkalny niewielki, lecz zewsząd chędogi,"},
        { "line" : "I stodołę miał wielką, i przy niej trzy stogi"},
        { "line" : "Użątku, co pod strzechą zmieścić się nie może;"},
        { "line" : "Widać, że okolica obfita we zboże,"},
        { "line" : "I widać z liczby kopic, co wzdłuż i wszerz smugów"},
        { "line" : "Świecą gęsto jak gwiazdy, widać z liczby pługów"},
        { "line" : "Orzących wcześnie łany ogromne ugoru,"},
        { "line" : "Czarnoziemne, zapewne należne do dworu,"},
        { "line" : "Uprawne dobrze na kształt ogrodowych grządek:"},
        { "line" : "Że w tym domu dostatek mieszka i porządek."},
        { "line" : "Brama na wciąż otwarta przechodniom ogłasza,"},
        { "line" : "Że gościnna i wszystkich w gościnę zaprasza."},
        { "line" : "Właśnie dwókonną bryką wjechał młody panek"},
        { "line" : "I obiegłszy dziedziniec zawrócił przed ganek,"},
        { "line" : "Wysiadł z powozu; konie porzucone same,"},
        { "line" : "Szczypiąc trawę ciągnęły powoli pod bramę."},
        { "line" : "We dworze pusto, bo drzwi od ganku zamknięto"},
        { "line" : "Zaszczepkami i kołkiem zaszczepki przetknięto."},
        { "line" : "Podróżny do folwarku nie biegł sług zapytać;"},
        { "line" : "Odemknął, wbiegł do domu, pragnął go powitać."},
        { "line" : "Dawno domu nie widział, bo w dalekim mieście"},
        { "line" : "Kończył nauki, końca doczekał nareszcie."},
        { "line" : "Wbiega i okiem chciwie ściany starodawne"},
        { "line" : "Ogląda czule, jako swe znajome dawne."},
        { "line" : "Też same widzi sprzęty, też same obicia,"},
        { "line" : "Z któremi się zabawiać lubił od powicia;"},
        { "line" : "Lecz mniej wielkie, mniej piękne, niż się dawniej zdały."},
        { "line" : "I też same portrety na ścianach wisiały."},
        { "line" : "Tu Kościuszko w czamarce krakowskiej, z oczyma"},
        { "line" : "Podniesionymi w niebo, miecz oburącz trzyma;"},
        { "line" : "Takim był, gdy przysięgał na stopniach ołtarzów,"},
        { "line" : "Że tym mieczem wypędzi z Polski trzech mocarzów"},
        { "line" : "Albo sam na nim padnie. Dalej w polskiej szacie"},
        { "line" : "Siedzi Rejtan żałośny po wolności stracie,"},
        { "line" : "W ręku trzymna nóż, ostrzem zwrócony do łona,"},
        { "line" : "A przed nim leży Fedon i żywot Katona."},
        { "line" : "Dalej Jasiński, młodzian piękny i posępny,"},
        { "line" : "Obok Korsak, towarzysz jego nieodstępny,"},
        { "line" : "Stoją na szańcach Pragi, na stosach Moskali,"},
        { "line" : "Siekąc wrogów, a Praga już się wkoło pali."},
        { "line" : "Nawet stary stojący zegar kurantowy"},
        { "line" : "W drewnianej szafie poznał u wniścia alkowy"},
        { "line" : "I z dziecinną radością pociągnął za sznurek,"},
        { "line" : "By stary Dąbrowskiego usłyszeć mazurek."},
        { "line" : "Biegał po całym domu i szukał komnaty,"},
        { "line" : "Gdzie mieszkał, dzieckiem będąc, przed dziesięciu laty."},
        { "line" : "Wchodzi, cofnął się, toczył zdumione źrenice"},
        { "line" : "Po ścianach: w tej komnacie mieszkanie kobiéce?"},
        { "line" : "Któż by tu mieszkał? Stary stryj nie był żonaty,"},
        { "line" : "A ciotka w Petersburgu mieszkała przed laty."},
        { "line" : "To nie był ochmistrzyni pokój! Fortepiano?"},
        { "line" : "Na niem noty i książki; wszystko porzucano"},
        { "line" : "Niedbale i bezładnie; nieporządek miły!"},
        { "line" : "Niestare były rączki, co je tak rzuciły."},
        { "line" : "Tuż i sukienka biała, świeżo z kołka zdjęta"},
        { "line" : "Do ubrania, na krzesła poręczu rozpięta."},
        { "line" : "A na oknach donice z pachnącymi ziołki,"},
        { "line" : "Geranium, lewkonija, astry i fijołki."},
        { "line" : "Podróżny stanął w jednym z okien - nowe dziwo:"},
        { "line" : "W sadzie, na brzegu niegdyś zarosłym pokrzywą,"},
        { "line" : "Był maleńki ogródek, ścieżkami porznięty,"},
        { "line" : "Pełen bukietów trawy angielskiej i mięty."},
        { "line" : "Drewniany, drobny, w cyfrę powiązany płotek"},
        { "line" : "Połyskał się wstążkami jaskrawych stokrotek."},
        { "line" : "Grządki widać, że były świeżo polewane;"},
        { "line" : "Tuż stało wody pełne naczynie blaszane,"},
        { "line" : "Ale nigdzie nie widać było ogrodniczki;"},
        { "line" : "Tylko co wyszła; jeszcze kołyszą się drzwiczki"},
        { "line" : "Świeżo trącone; blisko drzwi ślad widać nóżki"},
        { "line" : "Na piasku, bez trzewika była i pończoszki;"},
        { "line" : "Na piasku drobnym, suchym, białym na kształt śniegu,"},
        { "line" : "Ślad wyraźny, lecz lekki; odgadniesz, że w biegu"},
        { "line" : "Chybkim był zostawiony nóżkami drobnemi"},
        { "line" : "Od kogoś, co zaledwie dotykał się ziemi."},
        { "line" : "Podróżny długo w oknie stał patrząc, dumając,"},
        { "line" : "Wonnymi powiewami kwiatów oddychając,"},
        { "line" : "Oblicze aż na krzaki fijołkowe skłonił,"},
        { "line" : "Oczyma ciekawymi po drożynach gonił"},
        { "line" : "I znowu je na drobnych śladach zatrzymywał,"},
        { "line" : "Myślał o nich i, czyje były, odgadywał."},
        { "line" : "Przypadkiem oczy podniósł, i tuż na parkanie"},
        { "line" : "Stała młoda dziewczyna. - Białe jej ubranie"},
        { "line" : "Wysmukłą postać tylko aż do piersi kryje,"},
        { "line" : "Odsłaniając ramiona i łabędzią szyję."},
        { "line" : "W takim Litwinka tylko chodzić zwykła z rana,"},
        { "line" : "W takim nigdy nie bywa od mężczyzn widziana:"},
        { "line" : "Więc choć świadka nie miała, założyła ręce"},
        { "line" : "Na piersiach, przydawając zasłony sukience."},
        { "line" : "Włos w pukle nie rozwity, lecz w węzełki małe"},
        { "line" : "Pokręcony, schowany w drobne strączki białe,"},
        { "line" : "Dziwnie ozdabiał głowę, bo od słońca blasku"},
        { "line" : "Świecił się, jak korona na świętych obrazku."},
        { "line" : "Twarzy nie było widać. Zwrócona na pole"},
        { "line" : "Szukała kogoś okiem, daleko, na dole;"},
        { "line" : "Ujrzała, zaśmiała się i klasnęła w dłonie,"},
        { "line" : "Jak biały ptak zleciała z parkanu na błonie"},
        { "line" : "I wionęła ogrodem przez płotki, przez kwiaty,"},
        { "line" : "I po desce opartej o ścianę komnaty,"},
        { "line" : "Nim spostrzegł się, wleciała przez okno, świecąca,"},
        { "line" : "Nagła, cicha i lekka jak światłość miesiąca."},
        { "line" : "Nócąc chwyciła suknie, biegła do zwierciadła;"},
        { "line" : "Wtem ujrzała młodzieńca i z rąk jej wypadła"},
        { "line" : "Suknia, a twarz od strachu i dziwu pobladła."},
        { "line" : "Twarz podróżnego barwą spłonęła rumianą"},
        { "line" : "Jak obłok, gdy z jutrzenką napotka się ranną;"},
        { "line" : "Skromny młodzieniec oczy zmrużył i przysłonił,"},
        { "line" : "Chciał coś mówić, przepraszać, tylko się ukłonił"},
        { "line" : "I cofnął się; dziewica krzyknęła boleśnie,"},
        { "line" : "Niewyraźnie, jak dziecko przestraszone we śnie;"},
        { "line" : "Podróżny zląkł się, spójrzał, lecz już jej nie było."},
        { "line" : "Wyszedł zmieszany i czuł, że serce mu biło"},
        { "line" : "Głośno, i sam nie wiedział, czy go miało śmieszyć"},
        { "line" : "To dziwaczne spotkanie, czy wstydzić, czy cieszyć."},
        { "line" : "Tymczasem na folwarku nie uszło baczności,"},
        { "line" : "Że przed ganek zajechał któryś z nowych gości."},
        { "line" : "Już konie w stajnię wzięto, już im hojnie dano,"},
        { "line" : "Jako w porządnym domu, i obrok, i siano;"},
        { "line" : "Bo Sędzia nigdy nie chciał, według nowej mody,"},
        { "line" : "Odsyłać konie gości Żydom do gospody."},
        { "line" : "Słudzy nie wyszli witać, ale nie myśl wcale,"},
        { "line" : "Aby w domu Sędziego służono niedbale;"},
        { "line" : "Słudzy czekają, nim się pan Wojski ubierze,"},
        { "line" : "Który teraz za domem urządzał wieczerzę."},
        { "line" : "On Pana zastępuje i on w niebytności"},
        { "line" : "Pana zwykł sam przyjmować i zabawiać gości"},
        { "line" : "(Daleki krewny pański i przyjaciel domu)."},
        { "line" : "Widząc gościa, na folwark dążył po kryjomu"},
        { "line" : "(Bo nie mógł wyjść spotykać w tkackim pudermanie);"},
        { "line" : "Wdział więc, jak mógł najprędzej, niedzielne ubranie"},
        { "line" : "Nagotowane z rana, bo od rana wiedział,"},
        { "line" : "Że u wieczerzy będzie z mnóstwem gości siedział."},
        { "line" : "Pan Wojski poznał z dala, ręce rozkrzyżował"},
        { "line" : "I z krzykiem podróżnego ściskał i całował;"},
        { "line" : "Zaczęła się ta prędka, zmieszana rozmowa,"},
        { "line" : "W której lat kilku dzieje chciano zamknąć w słowa"},
        { "line" : "Krótkie i poplątane, w ciąg powieści, pytań,"},
        { "line" : "Wykrzykników i westchnień, i nowych powitań."},
        { "line" : "Gdy się pan Wojski dosyć napytał, nabadał,"},
        { "line" : "Na samym końcu dzieje tego dnia powiadał."},
        { "line" : "\"Dobrze, mój Tadeuszu (bo tak nazywano"},
        { "line" : "Młodzieńca, który nosił Kościuszkowskie miano"},
        { "line" : "Na pamiątkę, że w czasie wojny się urodził),"},
        { "line" : "Dobrze, mój Tadeuszu, żeś się dziś nagodził"},
        { "line" : "Do domu, właśnie kiedy mamy panien wiele."},
        { "line" : "Stryjaszek myśli wkrótce sprawić ci wesele;"},
        { "line" : "Jest z czego wybrać; u nas towarzystwo liczne"},
        { "line" : "Od kilku dni zbiera się na sądy graniczne"},
        { "line" : "Dla skończenia dawnego z panem Hrabią sporu;"},
        { "line" : "I pan Hrabia ma jutro sam zjechać do dworu;"},
        { "line" : "Podkomorzy już zjechał z żoną i z córkami."},
        { "line" : "Młodzież poszła do lasu bawić się strzelbami,"},
        { "line" : "A starzy i kobiety żniwo oglądają"},
        { "line" : "Pod lasem, i tam pewnie na młodzież czekają."},
        { "line" : "Pójdziemy, jeśli zechcesz, i wkrótce spotkamy"},
        { "line" : "Stryjaszka, Podkomorstwo i szanowne damy\"."},
        { "line" : "Pan Wojski z Tadeuszem idą pod las drogą"},
        { "line" : "I jeszcze się do woli nagadać nie mogą."},
        { "line" : "Słońce ostatnich kresów nieba dochodziło,"},
        { "line" : "Mniej silnie, ale szerzej niż we dnie świeciło,"},
        { "line" : "Całe zaczerwienione, jak zdrowe oblicze"},
        { "line" : "Gospodarza, gdy prace skończywszy rolnicze,"},
        { "line" : "Na spoczynek powraca. Już krąg promienisty"},
        { "line" : "Spuszcza się na wierzch boru i już pomrok mglisty,"},
        { "line" : "Napełniając wierzchołki i gałęzie drzewa,"},
        { "line" : "Cały las wiąże w jedno i jakoby zlewa;"},
        { "line" : "I bór czernił się na kształt ogromnego gmachu,"},
        { "line" : "Słońce nad nim czerwone jak pożar na dachu;"},
        { "line" : "Wtem zapadło do głębi; jeszcze przez konary"},
        { "line" : "Błysnęło jako świeca przez okienic szpary"},
        { "line" : "I zgasło. I wnet sierpy gromadnie dzwoniące"},
        { "line" : "We zbożach i grabliska suwane po łące"},
        { "line" : "Ucichły i stanęły: tak pan Sędzia każe,"},
        { "line" : "U niego ze dniem kończą pracę gospodarze."},
        { "line" : "\"Pan świata wie, jak długo pracować potrzeba;"},
        { "line" : "Słońce, Jego robotnik, kiedy znidzie z nieba,"},
        { "line" : "Czas i ziemianinowi ustępować z pola\"."},
        { "line" : "Tak zwykł mawiać pan Sędzia, a Sędziego wola"},
        { "line" : "Była ekonomowi poczciwemu świętą;"},
        { "line" : "Bo nawet wozy, w które już składać zaczęto"},
        { "line" : "Kopę żyta, niepełne jadą do stodoły;"},
        { "line" : "Cieszą się z nadzwyczajnej ich lekkości woły."},
        { "line" : "Właśnie z lasu wracało towarzystwo całe,"},
        { "line" : "Wesoło, lecz w porządku; naprzód dzieci małe"},
        { "line" : "Z dozorcą, potem Sędzia szedł z Podkomorzyną,"},
        { "line" : "Obok pan Podkomorzy otoczon rodziną;"},
        { "line" : "Panny tuż za starszemi, a młodzież na boku;"},
        { "line" : "Panny szły przed młodzieżą o jakie pół kroku"},
        { "line" : "(Tak każe przyzwoitość); nikt tam nie rozprawiał"},
        { "line" : "O porządku, nikt mężczyzn i dam nie ustawiał,"},
        { "line" : "A każdy mimowolnie porządku pilnował."},
        { "line" : "Bo Sędzia w domu dawne obyczaje chował"},
        { "line" : "I nigdy nie dozwalał, by chybiano względu"},
        { "line" : "Dla wieku, urodzenia, rozumu, urzędu."},
        { "line" : "\"Tym ładem - mawiał - domy i narody słyną,"},
        { "line" : "Z jego upadkiem domy i narody giną\"."},
        { "line" : "Więc do porządku wykli domowi i słudzy;"},
        { "line" : "I przyjezdny gość, krewny albo człowiek cudzy,"},
        { "line" : "Gdy Sędziego nawiedził, skoro pobył mało,"},
        { "line" : "Przejmował zwyczaj, którym wszystko oddychało."},
        { "line" : "Krótkie były Sędziego z synowcem witania:"},
        { "line" : "Dał mu poważnie rękę do pocałowania"},
        { "line" : "I w skroń ucałowawszy, uprzejmie pozdrowił;"},
        { "line" : "A choć przez wzgląd na gości niewiele z nim mówił,"},
        { "line" : "Widać było z łez, które wylotem kontusza"},
        { "line" : "Otarł prędko, jak kochał pana Tadeusza."},
        { "line" : "W ślad gospodarza wszystko ze żniwa i z boru,"},
        { "line" : "I z łąk, i z pastwisk razem wracało do dworu."},
        { "line" : "Tu owiec trzoda becząc w ulicę się tłoczy"},
        { "line" : "I wznosi chmurę pyłu; dalej z wolna kroczy"},
        { "line" : "Stado cielic tyrolskich z mosiężnymi dzwonki;"},
        { "line" : "Tam konie rżące lecą ze skoszonej łąki;"},
        { "line" : "Wszystko bieży ku studni, której ramię z drzewa"},
        { "line" : "Raz wraz skrzypi i napój w koryta rozlewa."},
        { "line" : "Sędzia, choć utrudzony, chociaż w gronie gości,"},
        { "line" : "Nie uchybił gospodarskiej, ważnej powinności:"},
        { "line" : "Udał się sam ku studni; najlepiej z wieczora"},
        { "line" : "Gospodarz widzi, w jakim stanie jest obora;"},
        { "line" : "Dozoru tego nigdy sługom nie poruczy,"},
        { "line" : "Bo Sędzia wie, że oko pańskie konia tuczy."},
        { "line" : "Wojski z woźnym Protazym ze świecami w sieni"},
        { "line" : "Stali i rozprawiali, nieco poróżnieni,"},
        { "line" : "Bo w niebytność Wojskiego Woźny po kryjomu"},
        { "line" : "Kazał stoły z wieczerzą powynosić z domu"},
        { "line" : "I ustawić co prędzej w pośrodku zamczyska,"},
        { "line" : "Którego widne były pod lasem zwaliska."},
        { "line" : "Po cóż te przenosiny? Pan Wojski się krzywił"},
        { "line" : "I przepraszał Sędziego; Sędzia się zadziwił,"},
        { "line" : "Lecz stało się; już późno i trudno zaradzić,"},
        { "line" : "Wolał gości przeprosić i w pustki prowadzić."},
        { "line" : "Po drodze Woźny ciągle Sędziemu tłumaczył,"},
        { "line" : "Dlaczego urządzenie pańskie przeinaczył:"},
        { "line" : "We dworze żadna izba nie ma obszerności"},
        { "line" : "Dostatecznej dla tylu, tak szanownych gości;"},
        { "line" : "W zamku sień wielka, jeszcze dobrze zachowana,"},
        { "line" : "Sklepienie całe - wprawdzie pękła jedna ściana,"},
        { "line" : "Okna bez szyb, lecz latem nic to nie zawadzi;"},
        { "line" : "Bliskość piwnic wygodna służącej czeladzi."},
        { "line" : "Tak mówiąc, na Sędziego mrugał; widać z miny,"},
        { "line" : "Że miał i taił inne, ważniejsze przyczyny."},
        { "line" : "O dwa tysiące kroków zamek stał za domem,"},
        { "line" : "Okazały budową, poważny ogromem,"},
        { "line" : "Dziedzictwo starożytnej rodziny Horeszków;"},
        { "line" : "Dziedzic zginął był w czasie krajowych zamieszków."},
        { "line" : "Dobra, całe zniszczone sekwestrami rządu,"},
        { "line" : "Bezładnością opieki, wyrokami sądu,"},
        { "line" : "W cząstce spadły dalekim krewnym po kądzieli,"},
        { "line" : "A resztę rozdzielono między wierzycieli."},
        { "line" : "Zamku żaden wziąść nie chciał, bo w szlacheckim stanie"},
        { "line" : "Trudno było wyłożyć koszt na utrzymanie;"},
        { "line" : "Lecz Hrabia, sąsiad bliski, gdy wyszedł z opieki,"},
        { "line" : "Panicz bogaty, krewny Horeszków daleki,"},
        { "line" : "Przyjechawszy z wojażu upodobał mury,"},
        { "line" : "Tłumacząc, że gotyckiej są architektury;"},
        { "line" : "Choć Sędzia z dokumentów przekonywał o tem,"},
        { "line" : "Że architekt był majstrem z Wilna, nie zaś Gotem."},
        { "line" : "Dość, że Hrabia chciał zamku, właśnie i Sędziemu"},
        { "line" : "Przyszła nagle taż chętka, nie wiadomo czemu."},
        { "line" : "Zaczęli proces w ziemstwie, potem w głównym sądzie,"},
        { "line" : "W senacie, znowu w ziemstwie i w guberskim rządzie;"},
        { "line" : "Wreszcie po wielu kosztach i ukazach licznych"},
        { "line" : "Sprawa wróciła znowu do sądów granicznych."},
        { "line" : "Słusznie Woźny powiadał, że w zamkowej sieni"},
        { "line" : "Zmieści się i palestra, i goście proszeni."},
        { "line" : "Sień wielka jak refektarz, z wypukłym sklepieniem"},
        { "line" : "Na filarach, podłoga wysłana kamieniem,"},
        { "line" : "Ściany bez żadnych ozdób, ale mur chędogi;"},
        { "line" : "Sterczały wkoło sarnie i jelenie rogi"},
        { "line" : "Z napisami: gdzie, kiedy te łupy zdobyte;"},
        { "line" : "Tuż myśliwców herbowne klejnoty wyryte"},
        { "line" : "I stoi wypisany każdy po imieniu;"},
        { "line" : "Herb Horeszków, Półkozic, jaśniał na sklepieniu."},
        { "line" : "Goście weszli w porządku i stanęli kołem;"},
        { "line" : "Podkomorzy najwyższe brał miejsce za stołem;"},
        { "line" : "Z wieku mu i z urzędu ten zaszczyt należy."},
        { "line" : "Idąc kłaniał się damom, starcom i młodzieży."},
        { "line" : "Przy nim stał kwestarz, Sędzia tuż przy Bernardynie,"},
        { "line" : "Bernardyn zmówił krótki pacierz po łacinie."},
        { "line" : "Mężczyznom dano wódkę; wtenczas wszyscy siedli"},
        { "line" : "I chołodziec litewski milcząc żwawo jedli."},
        { "line" : "Pan Tadeusz, choć młodzik, ale prawem gościa"},
        { "line" : "Wysoko siadł przy damach obok Jegomościa;"},
        { "line" : "Między nim i stryjaszkiem jedno pozostało"},
        { "line" : "Puste miejsce, jak gdyby na kogoś czekało."},
        { "line" : "Stryj nieraz na to miejsce i na drzwi poglądał,"},
        { "line" : "Jakby czyjegoś przyjścia był pewny i żądał."},
        { "line" : "I Tadeusz wzrok stryja ku drzwiom odprowadzał,"},
        { "line" : "I z nim na miejscu pustym oczy swe osadzał."},
        { "line" : "Dziwna rzecz! Miejsca wkoło są siedzeniem dziewic,"},
        { "line" : "Na które mógłby spójrzeć bez wstydu królewic,"},
        { "line" : "Wszystkie zacnie zrodzone, każda młoda, ładna;"},
        { "line" : "Tadeusz tam pogląda, gdzie nie siedzi żadna."},
        { "line" : "To miejsce jest zagadką, młódź lubi zagadki;"},
        { "line" : "Roztargniony, do swojej nadobnej sąsiadki"},
        { "line" : "Ledwie słów kilka wyrzekł, do Podkomorzanki;"},
        { "line" : "Nie zmienia jej talerzów, nie nalewa szklanki,"},
        { "line" : "I panien nie zabawia przez rozmowy grzeczne,"},
        { "line" : "Z których by wychowanie poznano stołeczne;"},
        { "line" : "To jedno puste miejsce nęci go i mami..."},
        { "line" : "Już nie puste, bo on je napełnił myślami."},
        { "line" : "Po tem miejscu biegało domysłów tysiące,"},
        { "line" : "Jako po deszczu żabki po samotnej łące;"},
        { "line" : "Śród nich jedna króluje postać, jak w pogodę"},
        { "line" : "Lilia jeziór skroń białą wznosząca nad wodę."},
        { "line" : "Dano trzecią potrawę. Wtem pan Podkomorzy,"},
        { "line" : "Wlawszy kropelkę wina w szklankę panny Róży,"},
        { "line" : "A młodszej przysunąwszy z talerzem ogórki,"},
        { "line" : "Rzekł: \"Muszę ja wam służyć, moje panny córki,"},
        { "line" : "Choć stary i niezgrabny\". Zatem się rzuciło"},
        { "line" : "Kilku młodych od stołu i pannom służyło."},
        { "line" : "Sędzia, z boku rzuciwszy wzrok na Tadeusza"},
        { "line" : "I poprawiwszy nieco wylotów kontusza,"},
        { "line" : "Nalał węgrzyna i rzekł:"},
        { "line" : "\"Dziś, nowym zwyczajem,"},
        { "line" : "My na naukę młodzież do stolicy dajem"},
        { "line" : "I nie przeczym, że nasi synowie i wnuki"},
        { "line" : "Mają od starych więcej książkowej nauki;"},
        { "line" : "Ale co dzień postrzegam, jak młódź cierpi na tem,"},
        { "line" : "Że nie ma szkół uczących żyć z ludźmi i światem."},
        { "line" : "Dawniej na dwory pańskie jachał szlachcic młody,"},
        { "line" : "Ja sam lat dziesięć byłem dworskim Wojewody,"},
        { "line" : "Ojca Podkomorzego, Mościwego Pana"},
        { "line" : "(Mówiąc, Podkomorzemu ścisnął za kolana);"},
        { "line" : "On mnie radą do usług publicznych sposobił,"},
        { "line" : "Z opieki nie wypuścił, aż człowiekiem zrobił."},
        { "line" : "W mym domu wiecznie będzie jego pamięć droga,"},
        { "line" : "Co dzień za duszę jego proszę Pana Boga."},
        { "line" : "Jeślim tyle na jego nie korzystał dworze"},
        { "line" : "Jak drudzy i wróciwszy w domu ziemię orzę,"},
        { "line" : "Gdy inni, więcej godni Wojewody względów,"},
        { "line" : "Doszli potem najwyższych krajowych urzędów,"},
        { "line" : "Przynajmniej tom skorzystał, że mi w moim domu"},
        { "line" : "Nikt nigdy nie zarzuci, bym uchybił komu"},
        { "line" : "W uczciwości, w grzeczności; a ja powiem śmiało:"},
        { "line" : "Grzeczność nie jest nauką łatwą ani małą."},
        { "line" : "Niełatwą, bo nie na tym kończy się, jak nogą"},
        { "line" : "Zręcznie wierzgnąć, z uśmiechem witać lada kogo;"},
        { "line" : "Bo taka grzeczność modna zda mi się kupiecka,"},
        { "line" : "Ale nie staropolska, ani też szlachecka."},
        { "line" : "Grzeczność wszystkim należy, lecz każdemu inna;"},
        { "line" : "Bo nie jest bez grzeczności i miłość dziecinna,"},
        { "line" : "I wzgląd męża dla żony przy ludziach, i pana"},
        { "line" : "Dla sług swoich, a w każdej jest pewna odmiana."},
        { "line" : "Trzeba się długo uczyć, ażeby nie zbłądzić"},
        { "line" : "I każdemu powinną uczciwość wyrządzić."},
        { "line" : "I starzy się uczyli; u panów rozmowa"},
        { "line" : "Była to historyja żyjąca krajowa,"},
        { "line" : "A między szlachtą dzieje domowe powiatu:"},
        { "line" : "Dawano przez to poznać szlachcicowi bratu,"},
        { "line" : "Że wszyscy o nim wiedzą, lekce go nie ważą;"},
        { "line" : "Więc szlachcic obyczaje swe trzymał pod strażą."},
        { "line" : "Dziś człowieka nie pytaj: co zacz? kto go rodzi?"},
        { "line" : "Z kim on żył, co porabiał? Każdy, gdzie chce, wchodzi,"},
        { "line" : "Byle nie szpieg rządowy i byle nie w nędzy."},
        { "line" : "Jak ów Wespazyjanus nie wąchał pieniędzy"},
        { "line" : "I nie chciał wiedzieć, skąd są, z jakich rąk i krajów,"},
        { "line" : "Tak nie chcą znać człowieka rodu, obyczajów!"},
        { "line" : "Dość, że ważny i że się stempel na nim widzi,"},
        { "line" : "Więc szanują przyjaciół jak pieniądze Żydzi\"."},
        { "line" : "To mówiąc Sędzia gości obejrzał porządkiem;"},
        { "line" : "Bo choć zawsze i płynnie mówił, i z rozsądkiem,"},
        { "line" : "Wiedział, że niecierpliwa młodzież teraźniejsza,"},
        { "line" : "Że ją nudzi rzecz długa, choć najwymowniejsza."},
        { "line" : "Ale wszyscy słuchali w milczeniu głębokiem;"},
        { "line" : "Sędzia Podkomorzego zdał się radzić okiem,"},
        { "line" : "Podkomorzy pochwałą rzeczy nie przerywał,"},
        { "line" : "Ale częstym skinieniem głowy potakiwał."},
        { "line" : "Sędzia milczał, on jeszcze skinieniem przyzwalał;"},
        { "line" : "Więc Sędzia jego puchar i swój kielich nalał"},
        { "line" : "I dalej mówił:"},
        { "line" : "\"Grzeczność nie jest rzeczą małą:"},
        { "line" : "Kiedy się człowiek uczy ważyć, jak przystało,"},
        { "line" : "Drugich wiek, urodzenie, cnoty, obyczaje,"},
        { "line" : "Wtenczas i swoją ważność zarazem poznaje;"},
        { "line" : "Jak na szalach żebyśmy nasz ciężar poznali,"},
        { "line" : "Musim kogoś posadzić na przeciwnej szali."},
        { "line" : "Zaś godna jest Waszmościów uwagi osobnej"},
        { "line" : "Grzeczność, którą powinna młodź dla płci nadobnej;"},
        { "line" : "Zwłaszcza gdy zacność domu, fortuny szczodroty"},
        { "line" : "Objaśniają wrodzone wdzięki i przymioty."},
        { "line" : "Stąd droga do afektów i stąd się kojarzy"},
        { "line" : "Wspaniały domów sojusz - tak myślili starzy."},
        { "line" : "A zatem...\""},
        { "line" : "Tu pan Sędzia nagłym zwrotem głowy"},
        { "line" : "Skinął na Tadeusza, rzucił wzrok surowy,"},
        { "line" : "Znać było, że przychodził już do wniosków mowy."},
        { "line" : "Wtem brząknął w tabakierkę złotą Podkomorzy"},
        { "line" : "I rzekł:"},
        { "line" : "\"Mój Sędzio, dawniej było jeszcze gorzej!"},
        { "line" : "Teraz nie wiem, czy moda i nas starych zmienia,"},
        { "line" : "Czy młodzież lepsza, ale widzę mniej zgorszenia."},
        { "line" : "Ach, ja pamiętam czasy, kiedy do Ojczyzny"},
        { "line" : "Pierwszy raz zawitała moda francuszczyzny!"},
        { "line" : "Gdy raptem paniczyki młode z cudzych krajów"},
        { "line" : "Wtargnęli do nas hordą gorszą od Nogajów!"},
        { "line" : "Prześladując w Ojczyźnie Boga, przodków wiarę,"},
        { "line" : "Prawa i obyczaje, nawet suknie stare."},
        { "line" : "Żałośnie było widzieć wyżółkłych młokosów,"},
        { "line" : "Gadających przez nosy, a często bez nosów,"},
        { "line" : "Opatrzonych w broszurki i w różne gazety,"},
        { "line" : "Głoszących nowe wiary, prawa, toalety."},
        { "line" : "Miała nad umysłami wielką moc ta tłuszcza;"},
        { "line" : "Bo Pan Bóg, kiedy karę na naród przepuszcza,"},
        { "line" : "Odbiera naprzód rozum od obywateli."},
        { "line" : "I tak mędrsi fircykom oprzeć się nie śmieli;"},
        { "line" : "I zląkł ich się jak dżumy jakiej cały naród,"},
        { "line" : "Bo już sam wewnątrz siebie czuł choroby zaród."},
        { "line" : "Krzyczano na modnisiów, a brano z nich wzory:"},
        { "line" : "Zmieniano wiarę, mowę, prawa i ubiory."},
        { "line" : "Była to maszkarada, zapustna swawola,"},
        { "line" : "Po której miał przyjść wkrótce wielki post - niewola!"},
        { "line" : "\"Pamiętam, chociaż byłem wtenczas małe dziecię,"},
        { "line" : "Kiedy do ojca mego w oszmiańskim powiecie"},
        { "line" : "Przyjechał pan Podczaszyc na francuskim wózku,"},
        { "line" : "Pierwszy człowiek, co w Litwie chodził po francusku."},
        { "line" : "Biegali wszyscy za nim jakby za rarogiem,"},
        { "line" : "Zazdroszczono domowi, przed którego progiem"},
        { "line" : "Stanęła Podczaszyca dwókolna dryndulka,"},
        { "line" : "Która się po francusku zwała karyjulka."},
        { "line" : "Zamiast lokajów w kielni siedziały dwa pieski,"},
        { "line" : "A na kozłach niemczysko chude na kształt deski;"},
        { "line" : "Nogi miał długie, cienkie, jak od chmielu tyki,"},
        { "line" : "W pończochach, ze srebrnymi klamrami trzewiki,"},
        { "line" : "Peruka z harbajtelem zawiązanym w miechu."},
        { "line" : "Starzy na on ekwipaż parskali ze śmiechu,"},
        { "line" : "A chłopi żegnali się, mowiąc, że po świecie"},
        { "line" : "Jeździ wenecki diabeł w niemieckiej karecie."},
        { "line" : "Sam Podczaszyc jaki był, opisywać długo;"},
        { "line" : "Dosyć, że nam się zdawał małpą lub papugą,"},
        { "line" : "W wielkiej peruce, którą do złotego runa"},
        { "line" : "On lubił porównywać, a my do kołtuna."},
        { "line" : "Jeśli kto i czuł wtenczas, że polskie ubranie"},
        { "line" : "Piękniejsze jest niż obcej mody małpowanie,"},
        { "line" : "Milczał; boby krzyczała młodzież, że przeszkadza"},
        { "line" : "Kulturze, że tamuje progresy, że zdradza!"},
        { "line" : "Taka była przesądów owoczesnych władza!"},
        { "line" : "Podczaszyc zapowiedział, że nas reformować,"},
        { "line" : "Cywilizować będzie i konstytuować;"},
        { "line" : "Ogłosił nam, że jacyś Francuzi wymowni"},
        { "line" : "Zrobili wynalazek: iż ludzie są rowni."},
        { "line" : "Choć o tem dawno w Pańskim pisano zakonie"},
        { "line" : "I każdy ksiądz toż samo gada na ambonie."},
        { "line" : "Nauka dawną była, szło o jej pełnienie!"},
        { "line" : "Lecz wtenczas panowało takie oślepienie,"},
        { "line" : "Że nie wierzono rzeczom najdawniejszym w świecie,"},
        { "line" : "Jeśli ich nie czytano w francuskiej gazecie."},
        { "line" : "Podczaszyc, mimo równość, wziął tytuł markiża;"},
        { "line" : "Wiadomo, że tytuły przychodzą z Paryża,"},
        { "line" : "A natenczas tam w modzie był tytuł markiża."},
        { "line" : "Jakoż, kiedy się moda odmieniła z laty,"},
        { "line" : "Tenże sam markiż przybrał tytuł demokraty;"},
        { "line" : "Wreszcie z odmienną modą, pod Napoleonem,"},
        { "line" : "Demokrata przyjechał z Paryża baronem;"},
        { "line" : "Gdyby żył dłużej, może nową alternatą"},
        { "line" : "Z barona przechrzciłby się kiedyś demokratą."},
        { "line" : "Bo Paryż częstą mody odmianą się chlubi,"},
        { "line" : "A co Francuz wymyśli, to Polak polubi."},
        { "line" : "\"Chwała Bogu, że teraz jeśli nasza młodzież"},
        { "line" : "Wyjeżdża za granicę, to już nie po odzież,"},
        { "line" : "Nie szukać prawodawstwa w drukarskich kramarniach"},
        { "line" : "Lub wymowy uczyć się w paryskich kawiarniach."},
        { "line" : "Bo teraz Napoleon, człek mądry a prędki,"},
        { "line" : "Nie daje czasu szukać mody i gawędki."},
        { "line" : "Teraz grzmi oręż, a nam starym serca rosną,"},
        { "line" : "Że znowu o Polakach tak na świecie głośno;"},
        { "line" : "Jest sława, a więc będzie i Rzeczpospolita!"},
        { "line" : "Zawżdy z wawrzynów drzewo wolności wykwita."},
        { "line" : "Tylko smutno, że nam, ach! tak się lata wleką"},
        { "line" : "W nieczynności! a oni tak zawsze daleko!"},
        { "line" : "Tak długo czekać! Nawet tak rzadka nowina!"},
        { "line" : "Ojcze Robaku (ciszej rzekł do Bernardyna),"},
        { "line" : "Słyszałem, żeś zza Niemna odebrał wiadomość;"},
        { "line" : "Może też co o naszym wojsku wie Jegomość?\""},
        { "line" : "\"Nic a nic - odpowiedział Robak obojętnie"},
        { "line" : "(Widać było, że słuchał rozmowy niechętnie) -"},
        { "line" : "Mnie polityka nudzi; jeżeli z Warszawy"},
        { "line" : "Mam list, to rzecz zakonna, to są nasze sprawy"},
        { "line" : "Bernardyńskie; cóż o tem gadać u wieczerzy?"},
        { "line" : "Są tu świeccy, do których nic to nie należy\"."},
        { "line" : "Tak mowiąc spojrzał zyzem, gdzie śród biesiadników"},
        { "line" : "Siedział gość Moskal; był to pan kapitan Ryków;"},
        { "line" : "Stary żołnierz, stał w bliskiej wiosce na kwaterze,"},
        { "line" : "Pan Sędzia go przez grzeczność prosił na wieczerzę."},
        { "line" : "Rykow jadł smaczno, mało wdawał się w rozmowę,"},
        { "line" : "Lecz na wzmiankę Warszawy rzekł, podniosłszy głowę:"},
        { "line" : "\"Pan Podkomorzy! Oj, Wy! Pan zawsze ciekawy"},
        { "line" : "O Bonaparta, zawsze Wam tam do Warszawy!"},
        { "line" : "He! Ojczyzna! Ja nie szpieg, a po polsku umiem -"},
        { "line" : "Ojczyzna! Ja to czuję wszystko, ja rozumiem!"},
        { "line" : "Wy Polaki, ja Ruski, teraz się nie bijem,"},
        { "line" : "Jest armistycjum, to my razem jemy, pijem."},
        { "line" : "Często na awanpostach nasz z Francuzem gada,"},
        { "line" : "Pije wódkę; jak krzykną: ura! - kanonada."},
        { "line" : "Ruskie przysłowie: z kim się biję, tego lubię;"},
        { "line" : "Gładź drużkę jak po duszy, a bij jak po szubie."},
        { "line" : "Ja mówię, będzie wojna u nas. Do majora"},
        { "line" : "Płuta adiutant sztabu przyjechał zawczora:"},
        { "line" : "Gotować się do marszu! Pójdziem, czy pod Turka,"},
        { "line" : "Czy na Francuza; oj, ten Bonapart figurka!"},
        { "line" : "Bez Suworowa to on może nas wytuza."},
        { "line" : "U nas w pułku gadano, jak szli na Francuza,"},
        { "line" : "Że Bonapart czarował, no, tak i Suwarów"},
        { "line" : "Czarował; tak i były czary przeciw czarów."},
        { "line" : "Raz w bitwie, gdzie podział się? szukać Bonaparta -"},
        { "line" : "A on zmienił się w lisa, tak Suwarów w charta;"},
        { "line" : "Tak Bonaparte znowu w kota się przerzuca,"},
        { "line" : "Dalej drzeć pazurami, a Suwarów w kuca."},
        { "line" : "Obaczcież, co się stało w końcu z Bonapartą...\""},
        { "line" : "Tu Ryków przerwał i jadł; wtem z potrawą czwartą"},
        { "line" : "Wszedł służący, i raptem boczne drzwi otwarto."},
        { "line" : "Weszła nowa osoba, przystojna i młoda;"},
        { "line" : "Jej zjawienie się nagłe, jej wzrost i uroda,"},
        { "line" : "Jej ubiór zwrócił oczy; wszyscy ją witali;"},
        { "line" : "Prócz Tadeusza, widać, że ją wszyscy znali."},
        { "line" : "Kibić miała wysmukłą, kształtną, pierś powabną,"},
        { "line" : "Suknię materyjalną, różową, jedwabną,"},
        { "line" : "Gors wycięty, kołnierzyk z korónek, rękawki"},
        { "line" : "Krótkie, w ręku kręciła wachlarz dla zabawki"},
        { "line" : "(Bo nie było gorąca); wachlarz pozłocisty"},
        { "line" : "Powiewając rozlewał deszcz iskier rzęsisty."},
        { "line" : "Głowa do włosów, włosy pozwijane w kręgi,"},
        { "line" : "W pukle, i przeplatane różowymi wstęgi,"},
        { "line" : "Pośród nich brylant, niby zakryty od oczu,"},
        { "line" : "Świecił się jako gwiazda w komety warkoczu -"},
        { "line" : "Słowem, ubiór galowy; szeptali niejedni,"},
        { "line" : "Że zbyt wykwintny na wieś i na dzień powszedni."},
        { "line" : "Nóżek, choć suknia krótka, oko nie zobaczy,"},
        { "line" : "Bo biegła bardzo szybko, suwała się raczéj,"},
        { "line" : "Jako osóbki, które na trzykrólskie święta"},
        { "line" : "Przesuwają w jasełkach ukryte chłopięta."},
        { "line" : "Biegła i wszystkich lekkim witając ukłonem,"},
        { "line" : "Chciała usieść na miejscu sobie zostawionem."},
        { "line" : "Trudno było; bo krzeseł dla gości nie stało:"},
        { "line" : "Na czterech ławach cztery ich rzędy siedziało,"},
        { "line" : "Trzeba było rzęd ruszyć lub ławę przeskoczyć;"},
        { "line" : "Zręcznie między dwie ławy umiała się wtłoczyć,"},
        { "line" : "A potem między rzędem siedzących i stołem"},
        { "line" : "Jak bilardowa kula toczyła się kołem."},
        { "line" : "W biegu dotknęła blisko naszego młodziana;"},
        { "line" : "Uczepiwszy falbaną o czyjeś kolana,"},
        { "line" : "Pośliznęła się nieco i w tem roztargnieniu"},
        { "line" : "Na pana Tadeusza wsparła się ramieniu."},
        { "line" : "Przeprosiwszy go grzecznie, na miejscu swem siadła"},
        { "line" : "Pomiędzy nim i stryjem, ale nic nie jadła,"},
        { "line" : "Tylko się wachlowała, to wachlarza trzonek"},
        { "line" : "Kręciła, to kołnierzyk z brabanckich koronek"},
        { "line" : "Poprawiała, to lekkim dotknieniem się ręki"},
        { "line" : "Muskała włosów pukle i wstąg jasnych pęki."},
        { "line" : "Ta przerwa rozmów trwała już minut ze cztery."},
        { "line" : "Tymczasem w końcu stoła naprzód ciche szmery,"},
        { "line" : "A potem się zaczęły wpółgłośne rozmowy;"},
        { "line" : "Mężczyźni rozsądzali swe dzisiejsze łowy."},
        { "line" : "Asesora z Rejentem wzmogła się uparta,"},
        { "line" : "Coraz głośniejsza kłótnia o kusego charta,"},
        { "line" : "Którego posiadaniem pan Rejent się szczycił"},
        { "line" : "I utrzymywał, że on zająca pochwycił;"},
        { "line" : "Asesor zaś dowodził na złość Rejentowi,"},
        { "line" : "Że ta chwała należy chartu Sokołowi."},
        { "line" : "Pytano zdania innych; więc wszyscy dokoła"},
        { "line" : "Brali stronę Kusego, albo też Sokoła,"},
        { "line" : "Ci jak znawcy, ci znowu jak naoczne świadki."},
        { "line" : "Sędzia na drugim końcu do nowej sąsiadki"},
        { "line" : "Rzekł półgłosem: \"Przepraszam, musieliśmy siadać,"},
        { "line" : "Niepodobna wieczerzy na później odkładać:"},
        { "line" : "Goście głodni, chodzili daleko na pole;"},
        { "line" : "Myśliłem, że dziś z nami nie będziesz przy stole\"."},
        { "line" : "To rzekłszy, z Podkomorzym przy pełnym kielichu"},
        { "line" : "O politycznych sprawach rozmawiał po cichu."},
        { "line" : "Gdy tak były zajęte stołu strony obie,"},
        { "line" : "Tadeusz przyglądał się nieznanej osobie:"},
        { "line" : "Przypomniał, że za pierwszym na miejsce wejrzeniem"},
        { "line" : "Odgadnął zaraz, czyim miało być siedzeniem."},
        { "line" : "Rumienił się, serce mu biło nadzwyczajnie;"},
        { "line" : "Więc rozwiązane widział swych domysłów tajnie!"},
        { "line" : "Więc było przeznaczono, by przy jego boku"},
        { "line" : "Usiadła owa piękność widziana w pomroku."},
        { "line" : "Wprawdzie zdała się teraz wzrostem dorodniejsza,"},
        { "line" : "Bo ubrana, a ubiór powiększa i zmniejsza."},
        { "line" : "I włos u tamtej widział krótki, jasnozłoty,"},
        { "line" : "A u tej krucze, długie zwijały się sploty."},
        { "line" : "Kolor musiał pochodzić od słońca promieni,"},
        { "line" : "Któremi przy zachodzie wszystko się czerwieni."},
        { "line" : "Twarzy wówczas nie dostrzegł, nazbyt rychło znikła,"},
        { "line" : "Ale myśl twarz nadobną odgadywać zwykła;"},
        { "line" : "Myślił, że pewnie miała czarniutkie oczęta,"},
        { "line" : "Białą twarz, usta kraśne jak wiśnie bliźnięta;"},
        { "line" : "U tej znalazł podobne oczy, usta, lica;"},
        { "line" : "W wieku może by była największa różnica:"},
        { "line" : "Ogrodniczka dziewczynką zdawała się małą,"},
        { "line" : "A pani ta niewiastą już w latach dojrzałą;"},
        { "line" : "Lecz młodzież o piękności metrykę nie pyta,"},
        { "line" : "Bo młodzieńcowi młodą jest każda kobiéta,"},
        { "line" : "Chłopcowi każda piękność zda się rówiennicą,"},
        { "line" : "A niewinnemu każda kochanka dziewicą."},
        { "line" : "Tadeusz, chociaż liczył lat blisko dwadzieście"},
        { "line" : "I od dzieciństwa mieszkał w Wilnie, wielkim mieście,"},
        { "line" : "Miał za dozorcę księdza, który go pilnował"},
        { "line" : "I w dawnej surowości prawidłach wychował."},
        { "line" : "Tadeusz zatem przywiozł w strony swe rodzinne"},
        { "line" : "Duszę czystą, myśl żywą i serce niewinne,"},
        { "line" : "Ale razem niemałą chętkę do swywoli."},
        { "line" : "Z góry już robił projekt, że sobie pozwoli"},
        { "line" : "Używać na wsi długo wzbronionej swobody;"},
        { "line" : "Wiedział, że był przystojny, czuł się rześki, młody,"},
        { "line" : "A w spadku po rodzicach wziął czerstwość i zdrowie."},
        { "line" : "Nazywał się Soplica; wszyscy Soplicowie"},
        { "line" : "Są, jak wiadomo, krzepcy, otyli i silni,"},
        { "line" : "Do żołnierki jedyni, w naukach mniej pilni."},
        { "line" : "Tadeusz się od przodków swoich nie odrodził:"},
        { "line" : "Dobrze na koniu jeździł, pieszo dzielnie chodził,"},
        { "line" : "Tępy nie był, lecz mało w naukach postąpił,"},
        { "line" : "Choć stryj na wychowanie niczego nie skąpił."},
        { "line" : "On wolał z flinty strzelać albo szablą robić;"},
        { "line" : "Wiedział, że go myślano do wojska sposobić,"},
        { "line" : "Że ojciec w testamencie wyrzekł taką wolę;"},
        { "line" : "Ustawicznie do bębna tęsknił, siedząc w szkole."},
        { "line" : "Ale stryj nagle pierwsze zamiary odmienił,"},
        { "line" : "Kazał, aby przyjechał i aby się żenił,"},
        { "line" : "I objął gospodarstwo; przyrzekł na początek"},
        { "line" : "Dać małą wieś, a potem cały swój majątek."},
        { "line" : "Te wszystkie Tadeusza cnoty i zalety"},
        { "line" : "Ściągnęły wzrok sąsiadki, uważnej kobiety."},
        { "line" : "Zmierzyła jego postać kształtną i wysoką,"},
        { "line" : "Jego ramiona silne, jego pierś szeroką"},
        { "line" : "I w twarz spójrzała, z której wytryskał rumieniec,"},
        { "line" : "Ilekroć z jej oczyma spotkał się młodzieniec:"},
        { "line" : "Bo z pierwszej lękliwości całkiem już ochłonął"},
        { "line" : "I patrzył wzrokiem śmiałym, w którym ogień płonął."},
        { "line" : "Również patrzyła ona, i cztery źrenice"},
        { "line" : "Gorzały przeciw sobie jak roratne świéce."},
        { "line" : "Pierwsza z nim po francusku zaczęła rozmowę;"},
        { "line" : "Wracał z miasta, ze szkoły: więc o książki nowe,"},
        { "line" : "O autorów pytała Tadeusza zdania"},
        { "line" : "I ze zdań wyciągała na nowo pytania;"},
        { "line" : "Cóż gdy potem zaczęła mówić o malarstwie,"},
        { "line" : "O muzyce, o tańcach, nawet o rzeźbiarstwie!"},
        { "line" : "Dowiodła, że zna równie pędzel, noty, druki;"},
        { "line" : "Aż osłupiał Tadeusz na tyle nauki,"},
        { "line" : "Lękał się, by nie został pośmiewiska celem,"},
        { "line" : "I jąkał się jak żaczek przed nauczycielem."},
        { "line" : "Szczęściem, że nauczyciel ładny i niesrogi;"},
        { "line" : "Odgadnęła sąsiadka powód jego trwogi,"},
        { "line" : "Wszczęła rzecz o mniej trudnych i mądrych przedmiotach:"},
        { "line" : "O wiejskiego pożycia nudach i kłopotach,"},
        { "line" : "I jak bawić się trzeba, i jak czas podzielić,"},
        { "line" : "By życie uprzyjemnić i wieś rozweselić."},
        { "line" : "Tadeusz odpowiadał śmielej, szła rzecz daléj,"},
        { "line" : "W pół godziny już byli z sobą poufali;"},
        { "line" : "Zaczęli nawet małe żarciki i sprzeczki."},
        { "line" : "W końcu, stawiła przed nim trzy z chleba gałeczki:"},
        { "line" : "Trzy osoby na wybor; wziął najbliższą sobie;"},
        { "line" : "Podkomorzanki na to zmarszczyły się obie,"},
        { "line" : "Sąsiadka zaśmiała się, lecz nie powiedziała,"},
        { "line" : "Kogo owa szczęśliwa gałka oznaczała."},
        { "line" : "Inaczej bawiono się w drugim końcu stoła,"},
        { "line" : "Bo tam, wzmógłszy się nagle, stronnicy Sokoła"},
        { "line" : "Na partyję Kusego bez litości wsiedli:"},
        { "line" : "Spór był wielki, już potraw ostatnich nie jedli."},
        { "line" : "Stojąc i pijąc obie kłóciły się strony,"},
        { "line" : "A najstraszniej pan Rejent był zacietrzewiony:"},
        { "line" : "Jak raz zaczął, bez przerwy rzecz swoję tokował"},
        { "line" : "I gestami ją bardzo dobitnie malował."},
        { "line" : "(Był dawniej adwokatem pan rejent Bolesta,"},
        { "line" : "Zwano go kaznodzieją, że zbyt lubił gesta)."},
        { "line" : "Teraz ręce przy boku miał, w tył wygiął łokcie,"},
        { "line" : "Spod ramion wytknął palce i długie paznokcie,"},
        { "line" : "Przedstawiając dwa smycze chartów tym obrazem."},
        { "line" : "Właśnie rzecz kończył: \"Wyczha! puściliśmy razem"},
        { "line" : "Ja i Asesor, razem, jakoby dwa kórki"},
        { "line" : "Jednym palcem spuszczone u jednej dwórórki;"},
        { "line" : "Wyczha! poszli, a zając jak struna - smyk w pole,"},
        { "line" : "Psy tuż (to mówiąc, ręce ciągnął wzdłuż po stole"},
        { "line" : "I palcami ruch chartów przedziwnie udawał),"},
        { "line" : "Psy tuż, i hec! od lasu odsadzili kawał;"},
        { "line" : "Sokoł smyk naprzód, rączy pies, lecz zagorzalec,"},
        { "line" : "Wysadził się przed Kusym o tyle, o palec;"},
        { "line" : "Wiedziałem, że spudłuje; szarak, gracz nie lada,"},
        { "line" : "Czchał niby prosto w pole, za nim psów gromada;"},
        { "line" : "Gracz szarak! skoro poczuł wszystkie charty w kupie,"},
        { "line" : "Pstręk na prawo, koziołka, z nim w prawo psy głupie,"},
        { "line" : "A on znowu fajt w lewo, jak wytnie dwa susy,"},
        { "line" : "Psy za nim fajt na lewo, on w las, a mój Kusy"},
        { "line" : "Cap !!\" - tak krzycząc pan Rejent, na stół pochylony,"},
        { "line" : "Z palcami swemi zabiegł aż do drugiej strony"},
        { "line" : "I \"cap!\" - Tadeuszowi wrzasnął tuż nad uchem."},
        { "line" : "Tadeusz i sąsiadka, tym głosu wybuchem"},
        { "line" : "Znienacka przestraszeni właśnie w pół rozmowy,"},
        { "line" : "Odstrychnęli od siebie mimowolnie głowy,"},
        { "line" : "Jako wierzchołki drzewa powiązane społem,"},
        { "line" : "Gdy je wicher rozerwie; i ręce pod stołem"},
        { "line" : "Blisko siebie leżące wstecz nagle uciekły,"},
        { "line" : "I dwie twarze w jeden się rumieniec oblekły."},
        { "line" : "Tadeusz, by nie zdradzić swego roztargnienia:"},
        { "line" : "\"Prawda - rzekł - mój Rejencie, prawda, bez wątpienia,"},
        { "line" : "Kusy piękny chart z kształtu, jeśli równie chwytny...\""},
        { "line" : "\"Chwytny? - krzyknął pan Rejent. - Mój pies faworytny"},
        { "line" : "Żeby nie miał być chwytny?\" Więc Tadeusz znowu"},
        { "line" : "Cieszył się, że tak piękny pies nie ma narowu,"},
        { "line" : "Żałował, że go tylko widział idąc z lasu"},
        { "line" : "I że przymiotów jego poznać nie miał czasu."},
        { "line" : "Na to zadrżał Asesor, puścił z rąk kieliszek,"},
        { "line" : "Utopił w Tadeusza wzrok jak bazyliszek."},
        { "line" : "Asesor mniej krzykliwy i mniej był ruchawy"},
        { "line" : "Od Rejenta, szczuplejszy i mały z postawy,"},
        { "line" : "Lecz straszny na reducie, balu i sejmiku,"},
        { "line" : "Bo powiadano o nim: ma żądło w języku."},
        { "line" : "Tak dowcipne żarciki umiał komponować,"},
        { "line" : "Iżby je w kalendarzu można wydrukować:"},
        { "line" : "Wszystkie złośliwe, ostre. Dawniej człek dostatni,"},
        { "line" : "Schedę ojca swojego i majątek bratni,"},
        { "line" : "Wszystko strwonił, na wielkim figurując świecie;"},
        { "line" : "Teraz wszedł w służbę rządu, by znaczyć w powiecie."},
        { "line" : "Lubił bardzo myślistwo, już to dla zabawy,"},
        { "line" : "Już to że odgłos trąbki i widok obławy"},
        { "line" : "Przypominał mu jego lata młodociane,"},
        { "line" : "Kiedy miał strzelców licznych i psy zawołane;"},
        { "line" : "Teraz mu z całej psiarni dwa charty zostały,"},
        { "line" : "I jeszcze z tych jednemu chciano przeczyć chwały."},
        { "line" : "Więc zbliżył się i, z wolna gładząc faworyty,"},
        { "line" : "Rzekł z uśmiechem, a był to uśmiech jadowity:"},
        { "line" : "\"Chart bez ogona jest jak szlachcic bez urzędu..."},
        { "line" : "Ogon też znacznie chartom pomaga do pędu,"},
        { "line" : "A Pan kusość uważasz za dowód dobroci?"},
        { "line" : "Zresztą zdać się możemy na sąd Pańskiej cioci."},
        { "line" : "Choć pani Telimena mieszkała w stolicy"},
        { "line" : "I bawi się niedawno w naszej okolicy,"},
        { "line" : "Lepiej zna się na łowach niż myśliwi młodzi:"},
        { "line" : "Tak to nauka sama z latami przychodzi\"."},
        { "line" : "Tadeusz, na którego niespodzianie spadał"},
        { "line" : "Grom taki, wstał zmieszany, chwilę nic nie gadał,"},
        { "line" : "Lecz patrzył na rywala coraz straszniej, srożéj..."},
        { "line" : "Wtem, wielkim szczęściem, dwakroć kichnął Podkomorzy."},
        { "line" : "\"Wiwat!\" - krzyknęli wszyscy; on się wszystkim skłonił"},
        { "line" : "I z wolna w tabakierę palcami zadzwonił:"},
        { "line" : "Tabakiera ze złota, z brylantów oprawa,"},
        { "line" : "A w środku jej był portret króla Stanisława."},
        { "line" : "Ojcu Podkomorzego sam król ją darował,"},
        { "line" : "Po ojcu Podkomorzy godnie ją piastował;"},
        { "line" : "Gdy w nię dzwonił, znak dawał, że miał głos zabierać;"},
        { "line" : "Umilkli wszyscy i ust nie śmieli otwierać."},
        { "line" : "On rzekł:"},
        { "line" : "\"Wielmożni Szlachta, Bracia Dobrodzieje!"},
        { "line" : "Forum myśliwskiem tylko są łąki i knieje,"},
        { "line" : "Więc ja w domu podobnych spraw nie decyduję"},
        { "line" : "I posiedzenie nasze na jutro solwuję,"},
        { "line" : "I dalszych replik stronom dzisiaj nie dozwolę."},
        { "line" : "Woźny! odwołaj sprawę na jutro na pole."},
        { "line" : "Jutro i Hrabia z całym myślistwem tu zjedzie,"},
        { "line" : "I Waszeć z nami ruszysz, Sędzio, mój sąsiedzie,"},
        { "line" : "I pani Telimena, i panny, i panie,"},
        { "line" : "Słowem, zrobim na urząd wielkie polowanie;"},
        { "line" : "I Wojski towarzystwa nam też nie odmówi\"."},
        { "line" : "To mówiąc tabakierę podawał starcowi."},
        { "line" : "Wojski na ostrym końcu śród myśliwych siedział,"},
        { "line" : "Słuchał zmrużywszy oczy, słowa nie powiedział,"},
        { "line" : "Choć młodzież nieraz jego zasięgała zdania,"},
        { "line" : "Bo nikt lepiej nad niego nie znał polowania."},
        { "line" : "On milczał, szczyptę wziętą z tabakiery ważył"},
        { "line" : "W palcach i długo dumał, nim ją w końcu zażył;"},
        { "line" : "Kichnął, aż cała izba rozległa się echem,"},
        { "line" : "I potrząsając głową rzekł z gorzkim uśmiechem:"},
        { "line" : "\"O, jak mnie to starego i smuci, i dziwi!"},
        { "line" : "Cóż by to o tym starzy mówili myśliwi,"},
        { "line" : "Widząc, że w tylu szlachty, w tylu panów gronie"},
        { "line" : "Mają sądzić się spory o charcim ogonie;"},
        { "line" : "Cóż by rzekł na to stary Rejtan, gdyby ożył?"},
        { "line" : "Wróciłby do Lachowicz i w grób się położył!"},
        { "line" : "Co by rzekł wojewoda Niesiołowski stary,"},
        { "line" : "Który ma dotąd pierwsze na świecie ogary"},
        { "line" : "I dwiestu strzelców trzyma obyczajem pańskim,"},
        { "line" : "I ma sto wozów sieci w zamku worończańskim,"},
        { "line" : "A od tylu lat siedzi jak mnich na swym dworze."},
        { "line" : "Nikt go na polowanie uprosić nie może,"},
        { "line" : "Białopiotrowiczowi samemu odmówił!"},
        { "line" : "Bo cóż by on na waszych polowaniach łowił?"},
        { "line" : "Piękna byłaby sława, ażeby pan taki"},
        { "line" : "Wedle dzisiejszej mody jeździł na szaraki!"},
        { "line" : "Za moich, panie, czasów w języku strzeleckim"},
        { "line" : "Dzik, niedźwiedź, łoś, wilk zwany był zwierzem szlacheckim,"},
        { "line" : "A zwierzę nie mające kłów, rogów, pazurów"},
        { "line" : "Zostawiano dla płatnych sług i dworskich ciurów;"},
        { "line" : "Żaden pan nigdy przyjąć nie chciałby do ręki"},
        { "line" : "Strzelby, którą zhańbiono, sypiąc w nią śrut cienki!"},
        { "line" : "Trzymano wprawdzie chartów, bo z łowów wracając,"},
        { "line" : "Trafia się, że spod konia mknie się biedak zając;"},
        { "line" : "Puszczano wtenczas za nim dla zabawki smycze"},
        { "line" : "I na konikach małe goniły panicze"},
        { "line" : "Przed oczami rodziców, którzy te pogonie"},
        { "line" : "Ledwie raczyli widzieć, cóż kłócić się o nie!"},
        { "line" : "Więc niech Jaśnie Wielmożny Podkomorzy raczy"},
        { "line" : "Odwołać swe rozkazy i niech mi wybaczy,"},
        { "line" : "Że nie mogę na takie jechać polowanie"},
        { "line" : "I nigdy na niem noga moja nie postanie!"},
        { "line" : "Nazywam się Hreczecha, a od króla Lecha"},
        { "line" : "Żaden za zającami nie jeździł Hreczecha\"."},
        { "line" : "Tu śmiech młodzieży mowę Wojskiego zagłuszył."},
        { "line" : "Wstano od stołu; pierwszy Podkomorzy ruszył;"},
        { "line" : "Z wieku mu i z urzędu ten zaszczyt należy;"},
        { "line" : "Idąc kłaniał się damom, starcom i młodzieży;"},
        { "line" : "Za nim szedł kwestarz, Sędzia tuż przy Bernardynie,"},
        { "line" : "Sędzia u progu rękę dał Podkomorzynie,"},
        { "line" : "Tadeusz Telimenie, Asesor Krajczance,"},
        { "line" : "A pan Rejent na końcu Wojskiej Hreczeszance."},
        { "line" : "Tadeusz z kilku gośćmi poszedł do stodoły,"},
        { "line" : "A czuł się pomieszany, zły i niewesoły,"},
        { "line" : "Rozbierał myślą wszystkie dzisiejsze wypadki:"},
        { "line" : "Spotkanie się, wieczerzę przy boku sąsiadki,"},
        { "line" : "A szczególniej mu słowo \"ciocia\" koło ucha"},
        { "line" : "Brzęczało ciągle jako naprzykrzona mucha."},
        { "line" : "Pragnąłby u Woźnego lepiej się wypytać"},
        { "line" : "O pani Telimenie, lecz go nie mógł schwytać;"},
        { "line" : "Wojskiego też nie widział, bo zaraz z wieczerzy"},
        { "line" : "Wszyscy poszli za gośćmi, jak sługom należy,"},
        { "line" : "Urządzając we dworze izby do spoczynku."},
        { "line" : "Starsi i damy spały we dworskim budynku,"},
        { "line" : "Młodzież Tadeuszowi prowadzić kazano,"},
        { "line" : "W zastępstwie gospodarza, w stodołę na siano."},
        { "line" : "W pół godziny tak było głucho w całym dworze"},
        { "line" : "Jako po zadzwonieniu na pacierz w klasztorze;"},
        { "line" : "Ciszę przerywał tylko głos nocnego stróża."},
        { "line" : "Usnęli wszyscy. Sędzia sam oczu nie zmruża:"},
        { "line" : "Jako wódz gospodarstwa obmyśla wyprawę"},
        { "line" : "W pole i w domu przyszłą urządza zabawę."},
        { "line" : "Dał rozkaz ekonomom, wójtom i gumiennym,"},
        { "line" : "Pisarzom, ochmistrzyni, strzelcom i stajennym,"},
        { "line" : "I musiał wszystkie dzienne rachunki przezierać,"},
        { "line" : "Nareszcie rzekł Woźnemu, że się chce rozbierać."},
        { "line" : "Woźny pas mu odwiązał, pas słucki, pas lity,"},
        { "line" : "Przy którym świecą gęste kutasy jak kity,"},
        { "line" : "Z jednej strony złotogłów w purpurowe kwiaty,"},
        { "line" : "Na wywrót jedwab czarny, posrebrzany w kraty;"},
        { "line" : "Pas taki można równie kłaść na strony obie:"},
        { "line" : "Złotą na dzień galowy, a czarną w żałobie."},
        { "line" : "Sam Woźny umiał pas ten odwiązywać, składać;"},
        { "line" : "Właśnie tym się zatrudniał i kończył tak gadać:"},
        { "line" : "\"Cóż złego, że przeniosłem stoły do zamczyska?"},
        { "line" : "Nikt na tem nic nie stracił, a Pan może zyska,"},
        { "line" : "Bo przecież o ten zamek dziś toczy się sprawa."},
        { "line" : "My od dzisiaj do zamku nabyliśmy prawa,"},
        { "line" : "I mimo całą strony przeciwnej zajadłość"},
        { "line" : "Dowiodę, że zamczysko wzięliśmy w posiadłość."},
        { "line" : "Wszakże kto gości prosi w zamek na wieczerzę,"},
        { "line" : "Dowodzi, że posiadłość tam ma albo bierze;"},
        { "line" : "Nawet strony przeciwne weźwiemy na świadki:"},
        { "line" : "Pamiętam za mych czasów podobne wypadki\"."},
        { "line" : "Już Sędzia spał. Więc Woźny cicho wszedł do sieni,"},
        { "line" : "Siadł przy świecy i dobył książeczkę z kieszeni,"},
        { "line" : "Która mu jak Ołtarzyk złoty zawsze służy,"},
        { "line" : "Której nigdy nie rzuca w domu i w podróży."},
        { "line" : "Była to trybunalska wokanda: tam rzędem"},
        { "line" : "Stały spisane sprawy, które przed urzędem"},
        { "line" : "Woźny sam głosem swoim przed laty wywołał"},
        { "line" : "Albo o których później dowiedzieć się zdołał."},
        { "line" : "Prostym ludziom wokanda zda się imion spisem,"},
        { "line" : "Woźnemu jest obrazów wspaniałych zarysem."},
        { "line" : "Czytał więc i rozmyślał: Ogiński z Wizgirdem,"},
        { "line" : "Dominikanie z Rymszą, Rymsza z Wysogierdem,"},
        { "line" : "Radziwiłł z Wereszczaką, Giedrojć z Rodułtowskim,"},
        { "line" : "Obuchowicz z kahałem, Juracha z Piotrowskim,"},
        { "line" : "Maleski z Mickiewiczem, a na koniec Hrabia"},
        { "line" : "Z Soplicą: i czytając, z tych imion wywabia"},
        { "line" : "Pamięć spraw wielkich, wszystkie procesu wypadki,"},
        { "line" : "I stają mu przed oczy sąd, strony i świadki;"},
        { "line" : "I ogląda sam siebie, jak w żupanie białym,"},
        { "line" : "W granatowym kontuszu stał przed trybunałem;"},
        { "line" : "Jedna ręka na szabli, a drugą do stoła"},
        { "line" : "Przywoławszy dwie strony: \"Uciszcie się!\" woła."},
        { "line" : "Marząc i kończąc pacierz wieczorny, pomału"},
        { "line" : "Usnął ostatni w Litwie Woźny trybunału."},
        { "line" : "Takie były zabawy, spory w one lata"},
        { "line" : "Śród cichej wsi litewskiej, kiedy reszta świata"},
        { "line" : "We łzach i krwi tonęła, gdy ów mąż, bóg wojny,"},
        { "line" : "Otoczon chmurą pułków, tysiącem dział zbrojny,"},
        { "line" : "Wprzągłszy w swój rydwan orły złote obok srebrnych,"},
        { "line" : "Od puszcz libijskich latał do Alpów podniebnych,"},
        { "line" : "Ciskając grom po gromie: w Piramidy, w Tabor,"},
        { "line" : "W Marengo, w Ulm, w Austerlitz. Zwycięstwo i Zabor"},
        { "line" : "Biegły przed nim i za nim. Sława czynów tylu,"},
        { "line" : "Brzemienna imionami rycerzy, od Nilu"},
        { "line" : "Szła hucząc ku północy, aż u Niemna brzegów"},
        { "line" : "Odbiła się, jak od skał, od Moskwy szeregów,"},
        { "line" : "Które broniły Litwę murami żelaza"},
        { "line" : "Przed wieścią dla Rosyi straszną jak zaraza."},
        { "line" : "Przecież nieraz nowina, niby kamień z nieba,"},
        { "line" : "Spadała w Litwę; nieraz dziad żebrzący chleba,"},
        { "line" : "Bez ręki lub bez nogi, przyjąwszy jałmużnę,"},
        { "line" : "Stanął i oczy wkoło obracał ostróżne."},
        { "line" : "Gdy nie widział we dworze rosyjskich żołnierzy"},
        { "line" : "Ani jarmułek, ani czerwonych kołnierzy,"},
        { "line" : "Wtenczas, kim był, wyznawał: był legijonistą,"},
        { "line" : "Przynosił kości stare na ziemię ojczystą,"},
        { "line" : "Której już bronić nie mógł... Jak go wtenczas cała"},
        { "line" : "Rodzina pańska, jak go czeladka ściskała,"},
        { "line" : "Zanosząc się od płaczu! On za stołem siadał"},
        { "line" : "I dziwniejsze od baśni historyje gadał."},
        { "line" : "On opowiadał, jako jenerał Dąbrowski"},
        { "line" : "Z ziemi włoskiej stara się przyciągnąć do Polski,"},
        { "line" : "Jak on rodaków zbiera na Lombardzkiem polu;"},
        { "line" : "Jak Kniaziewicz rozkazy daje z Kapitolu"},
        { "line" : "I zwycięzca, wydartych potomkom Cezarów"},
        { "line" : "Rzucił w oczy Francuzów sto krwawych sztandarów;"},
        { "line" : "Jak Jabłonowski zabiegł, aż kędy pieprz rośnie,"},
        { "line" : "Gdzie się cukier wytapia i gdzie w wiecznej wiośnie"},
        { "line" : "Pachnące kwitną lasy; z legiją Dunaju"},
        { "line" : "Tam wódz Murzyny gromi, a wzdycha do kraju."},
        { "line" : "Mowy starca krążyły we wsi po kryjomu;"},
        { "line" : "Chłopiec, co je posłyszał, znikał nagle z domu,"},
        { "line" : "Lasami i bagnami skradał się tajemnie,"},
        { "line" : "Ścigany od Moskali, skakał kryć się w Niemnie"},
        { "line" : "I nurkiem płynął na brzeg Księstwa Warszawskiego,"},
        { "line" : "Gdzie usłyszał głos miły: \"Witaj nam, kolego!\""},
        { "line" : "Lecz nim odszedł, wyskoczył na wzgórek z kamienia"},
        { "line" : "I Moskalom przez Niemen rzekł: \"Do zobaczenia!\""},
        { "line" : "Tak przekradł się Gorecki, Pac i Obuchowicz,"},
        { "line" : "Piotrowski, Obolewski, Rożycki, Janowicz,"},
        { "line" : "Mirzejewscy, Brochocki i Bernatowicze,"},
        { "line" : "Kupść, Gedymin i inni, których nie policzę;"},
        { "line" : "Opuszczali rodziców i ziemię kochaną,"},
        { "line" : "I dobra, które na skarb carski zabierano."},
        { "line" : "Czasem do Litwy kwestarz z obcego klasztoru"},
        { "line" : "Przyszedł, i kiedy bliżej poznał panów dworu,"},
        { "line" : "Gazetę im pokazał wyprutą z szkaplerza;"},
        { "line" : "Tam stała wypisana i liczba żołnierza,"},
        { "line" : "I nazwisko każdego wodza legijonu,"},
        { "line" : "I każdego z nich opis zwycięstwa lub zgonu."},
        { "line" : "Po wielu latach pierwszy raz miała rodzina"},
        { "line" : "Wieść o życiu, o chwale i o śmierci syna;"},
        { "line" : "Brał dom żałobę, ale powiedzieć nie śmiano,"},
        { "line" : "Po kim była żałoba, tylko zgadywano"},
        { "line" : "W okolicy; i tylko cichy smutek panów"},
        { "line" : "Lub cicha radość była gazetą ziemianów."},
        { "line" : "Takim kwestarzem tajnym był Robak podobno:"},
        { "line" : "Często on z panem Sędzią rozmawiał osobno;"},
        { "line" : "Po tych rozmowach zawsze jakowaś nowina"},
        { "line" : "Rozeszła się w sąsiedztwie. Postać Bernardyna"},
        { "line" : "Wydawała, że mnich ten nie zawsze w kapturze"},
        { "line" : "Chodził i nie w klasztornym zestarzał się murze."},
        { "line" : "Miał on nad prawym uchem, nieco wyżej skroni,"},
        { "line" : "Bliznę wyciętej skóry na szerokość dłoni"},
        { "line" : "I w brodzie ślad niedawny lancy lub postrzału;"},
        { "line" : "Ran tych nie dostał pewnie przy czytaniu mszału."},
        { "line" : "Ale nie tylko groźne wejrzenie i blizny,"},
        { "line" : "Lecz sam ruch i głos jego miał coś żołnierszczyzny."},
        { "line" : "Przy mszy, gdy z wzniesionymi zwracał się rękami"},
        { "line" : "Od ołtarza do ludu, by mówić: \"Pan z wami\","},
        { "line" : "To nieraz tak się zręcznie skręcił jednym razem,"},
        { "line" : "Jakby \"prawo w tył\" robił za wodza rozkazem,"},
        { "line" : "I słowa liturgiji takim wyrzekł tonem"},
        { "line" : "Do ludu, jak oficer stojąc przed szwadronem;"},
        { "line" : "Postrzegali to chłopcy służący mu do mszy."},
        { "line" : "Spraw także politycznych był Robak świadomszy"},
        { "line" : "Niźli żywotów świętych, a jeżdżąc po kweście,"},
        { "line" : "Często zastanawiał się w powiatowem mieście;"},
        { "line" : "Miał pełno interesów: to listy odbierał,"},
        { "line" : "Których nigdy przy obcych ludziach nie otwierał,"},
        { "line" : "To wysyłał posłańców, ale gdzie i po co,"},
        { "line" : "Nie powiadał; częstokroć wymykał się nocą"},
        { "line" : "Do dworów pańskich, z szlachtą ustawicznie szeptał"},
        { "line" : "I okoliczne wioski dokoła wydeptał,"},
        { "line" : "I w karczmach z wieśniakami rozprawiał niemało,"},
        { "line" : "A zawsze o tem, co się w cudzych krajach działo."},
        { "line" : "Teraz Sędziego, który już spał od godziny,"},
        { "line" : "Przychodzi budzić; pewnie ma jakieś nowiny."}
    ]
}